bump_version: null
lint:
  actions_awsfulltest: False
  files_exist: False
  files_unchanged: False
  multiqc_config: False
  template_strings: False
  nextflow_config:
    - manifest_version_dev  # This is the specific key for the 'dev' version check
    - manifest_name
    - manifest.name
    - manifest.version
    - manifest.homePage
    - manifest_homepage
  readme:
    - readme_nfcore_badge   # Specific key for the template badge
    - readme_nextflow_badge # Specific key for the version badge
  pipeline_name_conventions: False

nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: Erin Young
  description: reference-based consensus generation
  force: true
  is_nfcore: false
  name: Cecret
  org: UPHL-BioNGS/Cecret
  outdir: .
  version: 1.0.0