name: Test params file generation

on: [pull_request, workflow_dispatch]

jobs:
  params:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

          nextflow -version

      - name: Install nf-core tools
        run: pip install nf-core

      - name: Test params file creation
        run: |
          nf-core pipelines create-params-file . \
            --output test_params.json

      - name: Check file exists
        run: test -f test_params.json