name: Test SARS-CoV-2 primers

on: [pull_request, workflow_dispatch]

run-name: primers

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        primer:
          [ 
            "midnight_idt_V1",
            "midnight_ont_V1",
            "midnight_ont_V2",
            "midnight_ont_V3",
            "ncov_V3",
            "ncov_V4",
            "ncov_V4.1",
            "ncov_V5.3.2",
            "mpx_yale",
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Download reads
        run: |
          mkdir nanopore
          cd nanopore
          wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR224/050/SRR22452250/SRR22452250_1.fastq.gz
          wget -q ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR224/031/SRR22452231/SRR22452231_1.fastq.gz
          cd ../

      - name: Run Cecret
        run: |
          nextflow run . -profile docker -c .github/workflows/github_actions.config \
              --primer_set ${{ matrix.primer }} \
              --bcftools_variants false \
              --fastqc false \
              --ivar_variants false \
              --samtools_stats false \
              --samtools_coverage false \
              --samtools_depth false \
              --samtools_flagstat false \
              --kraken2 false \
              --nextclade false \
              --pangolin false \
              --freyja false \
              --vadr false \
              --relatedness false \
              --snpdists false \
              --iqtree2 false \
              --bamsnap false \
              --rename false \
              --filter false \
              --multiqc false \
              --nanopore nanopore

          ls cecret*

      - name: Clean
        run: rm -rf work .nextflow*
